# Generated by Django 3.2.4 on 2021-06-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargado', models.CharField(max_length=50)),
                ('nombrePatendida', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('detalle', models.CharField(max_length=600)),
                ('urgenciaCaso', models.CharField(choices=[('1', 'Leve'), ('2', 'Media'), ('2', 'Grave')], max_length=5)),
                ('tipoApoyo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Operadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('nacionalidad', models.CharField(blank=True, max_length=20)),
                ('correoElectronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('numeroContacto', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=20)),
                ('rut', models.IntegerField()),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patendidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('nacionalidad', models.CharField(blank=True, max_length=20)),
                ('correoElectronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('numeroContacto', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=20)),
                ('rut_DNI', models.CharField(blank=True, max_length=20, null=True)),
                ('estadoCivil', models.CharField(choices=[('1', 'Soltero'), ('2', 'Sasado')], max_length=7)),
                ('hijos', models.CharField(choices=[('1', 'Si'), ('2', 'No')], max_length=2)),
                ('cantHijos', models.IntegerField()),
                ('fechaIngreso', models.DateField()),
                ('motivoIngreso', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
