# Generated by Django 3.2.4 on 2021-06-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operadores',
            name='id',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='detalle',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='operadores',
            name='direccion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operadores',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patendidas',
            name='direccion',
            field=models.TextField(max_length=100),
        ),
    ]
